# .github/workflows/ci-cd.yml
name: Build, Secure and Deploy to AKS

on:
  push:
    branches:
      - main
  # Thêm pull_request để quét code ngay khi có yêu cầu thay đổi
  pull_request:
    branches:
      - main

jobs:
  # ----- CÔNG VIỆC MỚI ĐƯỢC THÊM VÀO -----
  codeql:
    name: Analyze Code with CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Cấp quyền để CodeQL ghi kết quả vào tab Security

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # 1. Khởi tạo CodeQL và tạo database từ mã nguồn
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: 'php' # Chỉ định ngôn ngữ cần quét là PHP

    # 2. CodeQL sẽ tự động build code để phân tích (không cần cấu hình thêm cho PHP)
    # Nếu là ngôn ngữ biên dịch như Java/C#, bạn sẽ cần thêm bước build ở đây.

    # 3. Chạy phân tích và tải kết quả lên GitHub
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

  # ----- CÔNG VIỆC CŨ (Build & Scan) -----
  build-and-scan:
    name: Build & Scan Image
    runs-on: ubuntu-latest
    # Thêm điều kiện để job này chỉ chạy khi push lên nhánh main
    if: github.event_name == 'push'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.ACR_NAME }}.azurecr.io/php-web-ban-hang:${{ github.sha }}

    - name: Scan image for vulnerabilities with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ secrets.ACR_NAME }}.azurecr.io/php-web-ban-hang:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

  # ----- CÔNG VIỆC CŨ (Deploy) -----
  deploy:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    # Thêm điều kiện để job này chỉ chạy khi push lên nhánh main
    if: github.event_name == 'push'
    # Thêm 'codeql' vào needs để đảm bảo deploy chỉ xảy ra khi code đã an toàn
    needs: [build-and-scan, codeql]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        cluster-name: ${{ secrets.CLUSTER_NAME }}

    - name: Replace Image Placeholder in deployment.yaml
      run: |
        IMAGE_NAME="${{ secrets.ACR_NAME }}.azurecr.io/php-web-ban-hang:${{ github.sha }}"
        sed -i "s|__IMAGE_PLACEHOLDER__|${IMAGE_NAME}|g" kubernetes/deployment.yaml

    - name: Deploy to AKS
      uses: Azure/k8s-deploy@v4
      with:
        action: 'deploy'
        manifests: |
          kubernetes/deployment.yaml
          kubernetes/service.yaml
          kubernetes/ingress.yaml
